// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB140h09AUFSTgRzF2r-6JJfqkGNIe4vVo',
    appId: '1:79290427415:web:60595ec548f6a17967d452',
    messagingSenderId: '79290427415',
    projectId: 'quietstudyspaces',
    authDomain: 'quietstudyspaces.firebaseapp.com',
    storageBucket: 'quietstudyspaces.firebasestorage.app',
    measurementId: 'G-C0RTW8YCH8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJB3cxlvHa0i2EkBgSDpvqNx_NI1qsz5o',
    appId: '1:79290427415:android:65ae00cbec834c7467d452',
    messagingSenderId: '79290427415',
    projectId: 'quietstudyspaces',
    storageBucket: 'quietstudyspaces.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDApee9UNzq3K6JX01sq2tLC8ptQ0-kizI',
    appId: '1:79290427415:ios:23103636b1d2975167d452',
    messagingSenderId: '79290427415',
    projectId: 'quietstudyspaces',
    storageBucket: 'quietstudyspaces.firebasestorage.app',
    iosBundleId: 'com.example.quiteStudySpacesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDApee9UNzq3K6JX01sq2tLC8ptQ0-kizI',
    appId: '1:79290427415:ios:23103636b1d2975167d452',
    messagingSenderId: '79290427415',
    projectId: 'quietstudyspaces',
    storageBucket: 'quietstudyspaces.firebasestorage.app',
    iosBundleId: 'com.example.quiteStudySpacesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB140h09AUFSTgRzF2r-6JJfqkGNIe4vVo',
    appId: '1:79290427415:web:85e711846d1e420467d452',
    messagingSenderId: '79290427415',
    projectId: 'quietstudyspaces',
    authDomain: 'quietstudyspaces.firebaseapp.com',
    storageBucket: 'quietstudyspaces.firebasestorage.app',
    measurementId: 'G-GFDF1Q86Y0',
  );
}
